version: 0.2

phases:
  build:
    commands:
       - npm install
       - npm run build:prod
       - cp -R .ebextensions ./build/.ebextensions/
artifacts:
  files:
    - '**/*'
  base-directory: build
